repos:
-   repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.1.10
    hooks:
    -   id: forbid-tabs
    -   id: remove-tabs
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
    - id: check-added-large-files
    - id: check-builtin-literals
    - id: check-case-conflict
    - id: check-yaml
      args: [--unsafe]
    - id: debug-statements
    - id: end-of-file-fixer
    - id: forbid-new-submodules
    - id: trailing-whitespace
    - id: mixed-line-ending
-   repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.9.1
    hooks:
    - id: isort
      files: \.py$
-   repo: https://github.com/ambv/black
    rev: 21.6b0
    hooks:
    - id: black
-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
    -   id: flake8
        additional_dependencies: ['flake8-typing-imports', 'flake8-docstrings']
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v0.910
  hooks:
  - id: mypy
    files: pysesame3
    args: ["--ignore-missing-imports", "--pretty"]
    additional_dependencies: ['types-requests', 'types-boto', 'types-certifi', 'AWSIoTPythonSDK']
