site_name: pysesame3
site_url: https://pysesame3.readthedocs.io/
repo_url: https://github.com/mochipon/pysesame3
repo_name: pysesame3
strict: true
extra_css:
  - styles/override.css
extra_javascript:
  - "https://code.jquery.com/jquery-3.6.0.min.js"
nav:
  - Home: index.md
  - Installation: installation.md
  - Usage: usage.md
  - Modules: api.md
  - Contributing: contributing.md
theme:
  name: material
  language: en
  palette:
    scheme: slate
    primary: teal
    accent: purple
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.indexes
    - navigation.tabs
    - navigation.instant
    - navigation.tabs.sticky
markdown_extensions:
  - admonition
  - attr_list
  - pymdownx.details
  - pymdownx.highlight:
      linenums: true
  - pymdownx.superfences
  - toc:
      baselevel: 2
      permalink: true
      slugify: !!python/name:pymdownx.slugs.uslugify
  - meta
plugins:
  - include-markdown
  - search:
      lang: en
  - mkdocstrings:
      watch:
        - pysesame3
