name: Enhancement request - リクエスト
description: Suggest an idea for this project - 機能の追加や改善の希望
title: "[Request]: "
labels: "enhancement"

body:
  - type: textarea
    attributes:
      label: Describe the solution you'd like - リクエストの内容
      description: >-
        A clear and concise description of what you want to happen.
        追加や改善、変更したい内容について簡潔に説明してください。
    validations:
      required: true

  - type: textarea
    attributes:
      label: What's the problem this feature will solve? - 解決したい内容
      description: >-
        A clear and concise description of what the problem is.
        このリクエストによって、どのような問題の解決を期待しているのか教えてください。

  - type: textarea
    attributes:
      label: Additional context - その他
      description: >-
        Add any other context or screenshots about the feature request here.
        追加資料があれば共有してください。
